language: csharp
mono: none
dotnet: 2.1.0
dist: trusty

script:
  # Run the unit tests.
  - cd todo.tests
  - dotnet test
  # Check to see if we can apply migrations.
  - cd ../todo
  - dotnet ef database update
