language: csharp
mono: none
dotnet: 2.0.0
dist: trusty

script:
  # Run the unit tests.
  - cd todo.test
  - dotnet test
  # Check to see if we can apply migrations.
  - cd ../todo
  - dotnet ef database update
