language: csharp
mono: none
dotnet: 2.1
dist: trusty

services:
  - postgresql

before_script:
  - psql -c 'create user todo with password \'todo123\'' superuser;' -U postgres
  - psql -c 'create database todo with owner todo;' -U postgres

script:
  # Run the unit tests.
  - cd todo.tests
  - dotnet test
  # Check to see if we can apply migrations.
  - cd ../todo
  - dotnet ef database update
