image: microsoft/dotnet:2.0-sdk

pipelines:
  default:
    - step:
        script:
          # Run the unit tests.
          - cd todo.tests
          - dotnet test
          # Check to see if we can apply migrations.
          - cd ../todo
          - dotnet ef database update
