version: "2"

services:
  webapp:
    build: .
    ports:
      - "127.0.0.1:34342:5000"
    environment:
      - CONNECTION_STRING=Docker
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    links:
      - postgres
    command: sh -c "sleep 5 && dotnet ef database update && dotnet run bin/Release/netcoreapp2.1/todo.dll"
    restart: unless-stopped

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=todo123
      - POSTGRES_USER=todo
      - POSTGRES_DB=todo
    restart: unless-stopped